#!/bin/bash

TARGET_URL=https://raw.githubusercontent.com/gslin/smokeping-config.d/master/Targets
TARGET_CONTENT=$(curl -s "${TARGET_URL}")

TARGET_OLDHASH=$(sha256sum /etc/smokeping/config.d/Targets | awk '{print $1}')
TARGET_NEWHASH=$(echo "${TARGET_CONTENT}" | sha256sum | awk '{print $1}')

/usr/bin/logger -p local0.info "Existing \"Targets\" hash: ${TARGET_OLDHASH}"
/usr/bin/logger -p local0.info "Network \"Targets\" hash: ${TARGET_NEWHASH}"

if [[ "${TARGET_OLDHASH}" = "${TARGET_NEWHASH}" ]]; then
    exit
fi

/usr/bin/logger -p local0.notice "Updating \"Targets\""

echo "${TARGET_CONTENT}" > /etc/smokeping/config.d/Targets

/usr/sbin/service smokeping restart
/usr/sbin/service smokeping-fcgi restart
